name: Deployment Workflow

on:
  push:
    branches:
      - main
  pull_request:  # Trigger on pull requests
    branches:
      - main  # Specify the target branch for the pull request

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check if demo projects are there
        run: |
          echo "Listing files in the parent directory:"
          cd ..
          ls
          echo "Navigating to demo projects directory:"
          cd components/atg/demo-projects
          echo "Listing files in demo projects directory:"
          ls