name: Deployment Workflow

on:
  push:
    branches:
      - main
  pull_request:  # Trigger on pull requests
    branches:
      - main  # Specify the target branch for the pull request

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check if demo projects are there
        run: 
          cd ..
          cd ..
          ls
          cd components/atg/demo-projects
          ls

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build